<a href="https://colab.research.google.com/github/kmanoj94/CS809/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
files.upload()

Saving Pollution.csv to Pollution.csv


{'Pollution.csv': b'CITY,SO2,MANUF,POP,TEMP,WIND,PRECIP-IN,PRECIP-DAY\r\nPhoenix,10,213,582,70.3,6,7.05,36\r\nLittle Rock,13,91,132,61,8.2,48.52,100\r\nSan Francisco,12,453,716,56.7,8.7,20.66,67\r\nDenver,17,454,515,51.9,9,12.95,86\r\nHartford,56,412,158,49.1,9,43.37,127\r\nWilmington,36,80,80,54,9,40.25,114\r\nWashington,29,434,757,57.3,9.3,38.89,111\r\nJacksonville,14,136,529,68.4,8.8,54.47,116\r\nMiami,10,207,335,75.5,9,59.8,128\r\nAtlanta,24,368,497,61.5,9.1,48.34,115\r\nChicago,110,3344,3369,50.6,10.4,34.44,122\r\nIndianapolis,28,361,746,52.3,9.7,38.74,121\r\nDes Moines,17,104,201,49,11.2,30.85,103\r\nWichita,8,125,277,56.6,12.7,30.58,82\r\nLouisville,30,291,593,55.6,8.3,43.11,123\r\nNew Orleans,9,204,361,68.3,8.4,56.77,113\r\nBaltimore,47,625,905,55,9.6,41.31,111\r\nDetroit,35,1064,1513,49.9,10.1,30.96,129\r\nMinneapolis-St. Paul,29,699,744,43.5,10.6,25.94,137\r\nKansas City,14,381,507,54.5,10,37,99\r\nSt. Louis,56,775,622,55.9,9.5,35.89,105\r\nOmaha,14,181,347,51.5,10.9,30.18,98

In [4]:
data=pd.read_csv("Pollution.csv")

In [5]:
data.shape

(41, 8)

In [6]:
data.head(41)

CITY  SO2  MANUF   POP  TEMP  WIND  PRECIP-IN  PRECIP-DAY
0                Phoenix   10    213   582  70.3   6.0       7.05          36
1            Little Rock   13     91   132  61.0   8.2      48.52         100
2          San Francisco   12    453   716  56.7   8.7      20.66          67
3                 Denver   17    454   515  51.9   9.0      12.95          86
4               Hartford   56    412   158  49.1   9.0      43.37         127
5             Wilmington   36     80    80  54.0   9.0      40.25         114
6             Washington   29    434   757  57.3   9.3      38.89         111
7           Jacksonville   14    136   529  68.4   8.8      54.47         116
8                  Miami   10    207   335  75.5   9.0      59.80         128
9                Atlanta   24    368   497  61.5   9.1      48.34         115
10               Chicago  110   3344  3369  50.6  10.4      34.44         122
11          Indianapolis   28    361   746  52.3   9.7      38.74         121
12            Des Moines   17    104   201  49.0  11.2      30.85         103
13               Wichita    8    125   277  56.6  12.7      30.58          82
14            Louisville   30    291   593  55.6   8.3      43.11         123
15           New Orleans    9    204   361  68.3   8.4      56.77         113
16             Baltimore   47    625   905  55.0   9.6      41.31         111
17               Detroit   35   1064  1513  49.9  10.1      30.96         129
18  Minneapolis-St. Paul   29    699   744  43.5  10.6      25.94         137
19           Kansas City   14    381   507  54.5  10.0      37.00          99
20             St. Louis   56    775   622  55.9   9.5      35.89         105
21                 Omaha   14    181   347  51.5  10.9      30.18          98
22           Albuquerque   11     46   244  56.8   8.9       7.77          58
23                Albany   46     44   116  47.6   8.8      33.36         135
24               Buffalo   11    391   463  47.1  12.4      36.11         166
25            Cincinnati   23    462   453  54.0   7.1      39.04         132
26             Cleveland   65   1007   751  49.7  10.9      34.99         155
27              Columbus   26    266   540  51.5   8.6      37.01         134
28          Philadelphia   69   1692  1950  54.6   9.6      39.93         115
29            Pittsburgh   61    347   520  50.4   9.4      36.22         147
30            Providence   94    343   179  50.0  10.6      42.75         125
31               Memphis   10    337   624  61.6   9.2      49.10         105
32             Nashville   18    275   448  59.4   7.9      46.00         119
33                Dallas    9    641   844  66.2  10.9      35.94          78
34               Houston   10    721  1233  68.9  10.8      48.19         103
35        Salt Lake City   28    137   176  51.0   8.7      15.17          89
36               Norfolk   31     96   308  59.3  10.6      44.68         116
37              Richmond   26    197   299  57.8   7.6      42.59         115
38               Seattle   29    379   531  51.1   9.4      38.79         164
39            Charleston   31     35    71  55.2   6.5      40.75         148
40             Milwaukee   16    569   717  45.7  11.8      29.07         123

In [7]:
CITY=data['CITY']
#dropping city fetaure because it's string value
Data=data.drop("CITY",axis=1)
print(Data.shape)


(41, 7)


In [8]:
cov_matrix=np.cov(Data.T)
print(cov_matrix)

[[ 5.50947561e+02  8.52772012e+03  6.71199451e+03 -7.35606707e+01
   3.17530488e+00  1.50017988e+01  2.29929878e+02]
 [ 8.52772012e+03  3.17502890e+05  3.11718814e+05 -7.73971341e+02
   1.91548110e+02 -2.15019902e+02  1.96895976e+03]
 [ 6.71199451e+03  3.11718814e+05  3.35371894e+05 -2.62349634e+02
   1.75930061e+02 -1.78052890e+02  6.45985976e+02]
 [-7.35606707e+01 -7.73971341e+02 -2.62349634e+02  5.22398780e+01
  -3.61135366e+00  3.28629884e+01 -8.24261585e+01]
 [ 3.17530488e+00  1.91548110e+02  1.75930061e+02 -3.61135366e+00
   2.04102439e+00 -2.18531098e-01  6.21439024e+00]
 [ 1.50017988e+01 -2.15019902e+02 -1.78052890e+02  3.28629884e+01
  -2.18531098e-01  1.38569384e+02  1.54792902e+02]
 [ 2.29929878e+02  1.96895976e+03  6.45985976e+02 -8.24261585e+01
   6.21439024e+00  1.54792902e+02  7.02590244e+02]]


In [10]:
corr_matrix = np.corrcoef(Data)
print(corr_matrix)

[[1.         0.76839071 0.96572591 ... 0.92881093 0.12909713 0.91992149]
 [0.76839071 1.         0.78628944 ... 0.86218141 0.64245087 0.79830472]
 [0.96572591 0.78628944 1.         ... 0.98155471 0.09355186 0.98936942]
 ...
 [0.92881093 0.86218141 0.98155471 ... 1.         0.25151044 0.98968239]
 [0.12909713 0.64245087 0.09355186 ... 0.25151044 1.         0.1187606 ]
 [0.91992149 0.79830472 0.98936942 ... 0.98968239 0.1187606  1.        ]]


In [12]:
eig_values, eig_vectors = np.linalg.eig(cov_matrix)

In [13]:
print('Eigenvectors \n%s' %eig_vectors)

Eigenvectors 
[[-1.68607518e-02 -9.98356252e-02 -2.08775573e-01 -9.58831063e-01
  -1.52191203e-01 -5.39529110e-02 -2.70413759e-02]
 [-6.96832794e-01 -7.10249079e-01  6.71822007e-02  7.31978785e-02
  -9.64365414e-03 -2.15302321e-03  1.13620790e-03]
 [-7.17028451e-01  6.92912523e-01 -5.66669352e-02 -4.90666865e-02
   1.07354573e-02  2.91575116e-03 -5.68200558e-05]
 [ 1.14177937e-03  2.58143904e-02  7.16007449e-02  1.10147840e-01
  -4.77854201e-01 -8.52534945e-01 -1.64050698e-01]
 [-4.06752976e-04 -1.01168043e-03 -5.38660645e-03  1.50660878e-02
   2.54019170e-02  1.76541256e-01 -9.83834710e-01]
 [ 4.33692181e-04  1.22593675e-03 -2.65807619e-01  1.62617123e-01
  -8.32729325e-01  4.53206155e-01  6.37678770e-02]
 [-2.88369500e-03 -6.91550513e-02 -9.34279828e-01  1.84590521e-01
   2.32812295e-01 -1.83568735e-01 -1.89145450e-02]]


In [14]:
print('\nEigen Values \n %s' %eig_values)


Eigen Values 
 [6.38471962e+05 1.48120379e+04 7.01959940e+02 2.05001941e+02
 1.16704681e+02 1.20570493e+01 1.44870440e+00]


In [18]:
(100*(eig_values[0] / sum(eig_values)))+(100*(eig_values[1] / sum(eig_values)))

99.84148880397618